// 1. Ambil input
let Mu = ...
let b = ...
let d = ...
let fc = ...
let fy = ...

// 2. Hitung As yang dibutuhkan
// menggunakan iterasi atau rumus pendekatan

// 3. Tentukan jumlah batang otomatis
// misal pakai D16, D19, dll
